# Site settings
title: Tech Hippie
header-img: img/home-bg.png
email: lindsay.c.dennis@gmail.com
copyright_name: Lindsay-c-Dennis
description: > # this means to ignore newlines until "baseurl:"
  Starting the development career...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Lindsay-c-Dennis
learn_profile: Lindsay-c-Dennis
email_username: lindsay.c.dennis@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
